services:
  - type: web
    name: ocr-api
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev && pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
